[common]
# tls | payload | tlsmod
mode = tls
# tampilkan debug response
debug = true
[server] #ssh
host = 127.0.0.1
port = 80
[ssh]
user = userssh
password = passwdssh
[tls]
sni = business.com
[local]
listen_port = 8989
[tlsmod]
proxy = bugproxy.com
port = 443
[payload]
custom_payload = GET / HTTP/1.1[crlf]Host: business.com[crlf]Upgrade: websocket[crlf]Connection: Upgrade[crlf]Sec-WebSocket-Version: 13[crlf][crlf]
